title: [Blockchain Game Development]
description: [I am a student from the University of Chile, and am researching how the fairly new blockchain technologies can and has affected game development.]
theme: jekyll-theme-cayman
